#!/bin/bash

files_per_block="20"

#----------------------------------------------------------------------------------------------------

function FlushBuffer()
{
	local buffer="$1"
	local block_idx="$2"

	local block_g
	let block_g=block_idx/100

	local dir="$base_dir/${block_g}/block${block_idx}"
	mkdir -p "$dir"

	echo "* $dir"
	
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.untracked.vstring("
		echo -e "$buffer"
		echo ")"
	) > "$dir/input_files.py"

	cp "template_cfg.py" "$dir/cfg.py"
}

#----------------------------------------------------------------------------------------------------

function MakeFiles()
{
	base_dir="$1"
	query="$2"

	buffer=""
	buffer_size="0"

	block_idx="0"

	for file in `dasgoclient --query "$query"|grep store`
	do
		if [ -n "$buffer" ]
		then
			buffer="$buffer,\n"
		fi
		#buffer="$buffer\t\"root://cmsxrootd.fnal.gov//$file\""
		buffer="$buffer\t\"$file\""

		let buffer_size+=1

		if [ "$buffer_size" -ge "$files_per_block" ]
		then
			FlushBuffer "$buffer" "$block_idx"
	
			buffer=""
			let buffer_size=0
			let block_idx+=1
		fi
	done

	if [ "$buffer_size" -gt "0" ]
	then
		FlushBuffer "$buffer" "$block_idx"
	
		buffer=""
		let buffer_size=0
		let block_idx+=1
	fi
}

#----------------------------------------------------------------------------------------------------

# 2016, pre-TS2
MakeFiles "data/2016_preTS2/SingleMuon/2016B" "file dataset=/SingleMuon/Run2016B-21Feb2020_ver2_UL2016_HIPM-v1/AOD" &
MakeFiles "data/2016_preTS2/SingleMuon/2016C" "file dataset=/SingleMuon/Run2016C-21Feb2020_UL2016_HIPM-v1/AOD" &
MakeFiles "data/2016_preTS2/SingleMuon/2016G" "file dataset=/SingleMuon/Run2016G-21Feb2020_UL2016-v1/AOD" &

# 2016, post-TS2
MakeFiles "data/2016_postTS2/SingleMuon/2016H" "file dataset=/SingleMuon/Run2016H-21Feb2020_UL2016-v1/AOD" &
   
# 2017, pre-TS2
MakeFiles "data/2017_preTS2/SingleMuon/2017B" "file dataset=/SingleMuon/Run2017B-09Aug2019_UL2017-v1/AOD" &
MakeFiles "data/2017_preTS2/SingleMuon/2017C" "file dataset=/SingleMuon/Run2017C-09Aug2019_UL2017-v1/AOD" &
MakeFiles "data/2017_preTS2/SingleMuon/2017D" "file dataset=/SingleMuon/Run2017D-09Aug2019_UL2017-v1/AOD" &

# 2017, post-TS2
MakeFiles "data/2017_postTS2/SingleMuon/2017E" "file dataset=/SingleMuon/Run2017E-09Aug2019_UL2017-v1/AOD" &
MakeFiles "data/2017_postTS2/SingleMuon/2017F" "file dataset=/SingleMuon/Run2017F-09Aug2019_UL2017-v1/AOD" &
